-- Borrado de vistas

DROP VIEW gr7_top_clientes_anual;

DROP VIEW gr7_estado_posiciones;

-- Borrado de funciones

DROP FUNCTION fn_gr7_notificacionclientes(integer);

DROP FUNCTION fn_gr7_posicioneslibres(fecha date);

-- Borrado de triggers

DROP TRIGGER TRFN_GR7_MOV_ENTRADA_CTRL_PESO;

DROP TRIGGER TRFN_GR7_MOV_INTERNO_CTRL_PESO;

-- Borrado de chequeos

ALTER TABLE GR7_ALQUILER
DROP CONSTRAINT ck_gr7_alquiler_fecha_valida;

ALTER TABLE GR7_POSICION
DROP CONSTRAINT ck_gr7_posicion_tipo_valido;

-- Borrado de foreign keys

ALTER TABLE GR7_ALQUILER
    DROP CONSTRAINT FK_GR7_ALQUILER_CLIENTE;

ALTER TABLE GR7_ALQUILER_POSICIONES
    DROP CONSTRAINT FK_GR7_ALQUILER_POSICIONES_ALQUILER;

ALTER TABLE GR7_ALQUILER_POSICIONES
    DROP CONSTRAINT FK_GR7_ALQUILER_POSICIONES_POSICION;

ALTER TABLE GR7_FILA
    DROP CONSTRAINT FK_GR7_FILA_ESTANTERIA;

ALTER TABLE GR7_MOV_ENTRADA
    DROP CONSTRAINT FK_GR7_MOV_ENTRADA_ALQUILER_POSICIONES;

ALTER TABLE GR7_MOV_ENTRADA
    DROP CONSTRAINT FK_GR7_MOV_ENTRADA_MOVIMIENTO;

ALTER TABLE GR7_MOV_ENTRADA
    DROP CONSTRAINT FK_GR7_MOV_ENTRADA_PALLET;

ALTER TABLE GR7_MOV_INTERNO
    DROP CONSTRAINT FK_GR7_MOV_INTERNO_MOVIMIENTO;

ALTER TABLE GR7_MOV_INTERNO
    DROP CONSTRAINT FK_GR7_MOV_INTERNO_MOV_ENTRADA;

ALTER TABLE GR7_MOV_INTERNO
    DROP CONSTRAINT FK_GR7_MOV_INTERNO_MOV_INTERNO;

ALTER TABLE GR7_MOV_INTERNO
    DROP CONSTRAINT FK_GR7_MOV_INTERNO_POSICION;

ALTER TABLE GR7_MOV_SALIDA
    DROP CONSTRAINT FK_GR7_MOV_SALIDA_MOVIMIENTO;

ALTER TABLE GR7_MOV_SALIDA
    DROP CONSTRAINT FK_GR7_MOV_SALIDA_MOV_ENTRADA;

ALTER TABLE GR7_POSICION
    DROP CONSTRAINT FK_GR7_POSICION_FILA;

-- Borrado de tablas

DROP TABLE GR7_ALQUILER;

DROP TABLE GR7_ALQUILER_POSICIONES;

DROP TABLE GR7_CLIENTE;

DROP TABLE GR7_ESTANTERIA;

DROP TABLE GR7_FILA;

DROP TABLE GR7_MOVIMIENTO;

DROP TABLE GR7_MOV_ENTRADA;

DROP TABLE GR7_MOV_INTERNO;

DROP TABLE GR7_MOV_SALIDA;

DROP TABLE GR7_PALLET;

DROP TABLE GR7_POSICION;
